### ISSUE TITLE
Review string patterns supported by diagnostics library

### ISSUE THREAD

**Issue by rascaille** [Hyperstore/Jade#9]
When you define a message for a constraint, you can use predefined "pattern" to place into the message the name of the element to validate etc...
(_id, _name, $id, $name...)

In a next version, you could open this feature to lodash templating...

**Comment by malain** [comment]
A diagnostic message is emitted by a constraint and has some extended formatting features. Since constraint are executed on a domain element, every diagnostic has a reference to this element and if the constraint is a property constraint, the *propertyName* property is set.

You can use this dynamic informations to create a message with pattern like **{{$property_name}}**.
(Only simple properties are allowed. xxx.yyy are not take into account.)

**example** : "{{Email}} is already taken for customer {{Name}}"

Special patterns  (*) = Only valid on a property constraint. :
- $propertyName : Name of the current checked property (*)
- $id           : Current element id
- $schema       : Current element schema id
- $identity     : Try to display an identity for the current element by checking in order :
  1. - IsKey property(ies) value
  2. - An id property
  3. - A name property
  4. - $id
- $value        : value of the checked property (*)
- $oldValue     : old value of the checked property (*)

can be used.

Property beginning with '@', references property of the current constraint (useful for valueobject constraint)
